EC_English/Controllers/EnrolmentsController.cs
using BusinessLogic.Helpers;
using BusinessLogic.Utils;
using Common.Models;
using Common.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EC_English.Controllers
{
    public class EnrolmentsController : Controller
    {
        private void PopulateDataForCreate()
        {
            //Get list of students and courses to populate the dropdowns and add them to ViewBag
            ViewBag.Students = StudentBL.GetAllAsync().Result.OrderBy(x => x.Name).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name + " " + x.Surname });
            ViewBag.Courses = CourseBL.GetAllAsync().Result.OrderBy(x => x.Name).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name });
        }

        [HttpGet]
        public IActionResult Create(int? studentId)
        {
            PopulateDataForCreate();

            if (studentId.HasValue)
            {
                var enrolment = new Enrolment()
                {
                    StudentId = studentId.Value
                };

                return View(enrolment);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Enrolment enrolment)
        {
            if (ModelState.IsValid)
            {
                if (enrolment.EndDate < enrolment.StartDate)
                {
                    ViewBag.Message = "Enrolment end date cannot be before holiday start date.";
                }
                else
                {
                    enrolment = await EnrolmentBL.SaveAsync(enrolment);

                    //check schedule for any conflicts
                    ScheduleHelper.CheckSchedule(enrolment.StudentId, enrolment);

                    return RedirectToAction("Details", "Students", new { id = enrolment.StudentId });
                }
            }

            PopulateDataForCreate();
            return View(enrolment);
        }

        [HttpGet]
        public JsonResult GetCourseEndDate(int? courseId, DateTime? startDate)
        {
            var result = string.Empty;

            if(courseId.HasValue && startDate.HasValue)
            {
                result = CourseBL.GetCourseEndDate(courseId.Value, startDate.Value).ToString("yyyy-MM-dd");
            }   

            return Json(result);
        }
    }
}

EC_English/Controllers/HolidaysController.cs
using BusinessLogic.Helpers;
using BusinessLogic.Utils;
using Common.Models;
using Common.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace EC_English.Controllers
{
    public class HolidaysController : Controller
    {
        private void PopulateDataForCreate()
        {
            //Get list of students to populate the dropdown and add it to ViewBag
            ViewBag.Students = StudentBL.GetAllAsync().Result.OrderBy(x => x.Name).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name + " " + x.Surname });
        }

        [HttpGet]
        public IActionResult Create(int? studentId)
        {
            PopulateDataForCreate();

            if (studentId.HasValue)
            {
                var holiday = new Holiday()
                {
                    StudentId = studentId.Value
                };

                return View(holiday);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Holiday holiday)
        {
            if (ModelState.IsValid)
            {
                if (holiday.EndDate < holiday.StartDate)
                {
                    ViewBag.Message = "Holiday end date cannot be before holiday start date.";
                }
                else if (HolidayBL.HasConflictingStudentHolidays(holiday))
                {
                    ViewBag.Message = "Holiday dates conflict with a booked holiday.";
                }
                else
                {
                    holiday = await HolidayBL.SaveAsync(holiday);

                    //checks schedule for any conflicts
                    ScheduleHelper.CheckSchedule(holiday.StudentId, holiday);

                    return RedirectToAction("Details", "Students", new { id = holiday.StudentId });
                }
            }

            PopulateDataForCreate();
            return View(holiday);
        }

        [HttpGet]
        public JsonResult GetNextFriday(DateTime? date)
        {
            //if given date has a value return the next Friday from the specified date
            var result = (date.HasValue) ? date.Value.GetNext(DayOfWeek.Friday).ToString("yyyy-MM-dd") : string.Empty;
            return Json(result);
        }
    }
}

EC_English/Controllers/StudentsController.cs
using BusinessLogic.Helpers;
using Common.CustomModels;
using Common.Models;
using Common.Utils;
using EC_English.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EC_English.Controllers
{
    public class StudentsController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index(string search)
        {
            //if search keyword is specified filter the list of students else return all students
            var students = (String.IsNullOrWhiteSpace(search))
                    ? await StudentBL.GetAllAsync()
                    : await StudentBL.GetAllAsync(x => x.SearchKeywords.Contains(search, StringComparison.CurrentCultureIgnoreCase));

            return View(students);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
                return NotFound();

            try
            {
                //get student and cast it to a StudentScheduleModel
                var student = StudentBL.GetAllAsync(x => x.Id == id).Result.FirstOrDefault();
                var studentSchedule = Utils.ConvertSuperClassToSubClass<StudentScheduleModel>(student);

                //get student current and future holidays and enrolments
                var enrolments = await EnrolmentBL.GetAllAsync(x => x.StudentId == id && x.StartDate >= DateTime.Today, ExpressionHandler<Enrolment>.Include(x => x.Course));
                var holidays = await HolidayBL.GetAllAsync(x => x.StudentId == id && x.StartDate >= DateTime.Today);

                //add the student holidays and enrolments to ScheduleModel
                var schedule = new List<ScheduleModel>();

                schedule.AddRange(holidays.Select((x) => new ScheduleModel
                {
                    Type = x.GetType().Name,
                    StartDate = x.StartDate,
                    EndDate = x.EndDate
                }));

                schedule.AddRange(enrolments.Select((x) => new ScheduleModel
                {
                    Type = (x.Split) ? $"{x.Course.Name} (Part {x.Part})" : x.Course.Name,
                    StartDate = x.StartDate,
                    EndDate = x.EndDate
                }));

                //order the list by StartDate ASC and then by Type DESC
                studentSchedule.Schedule = schedule.OrderBy(x => x.StartDate).ThenByDescending(x => x.Type).ToList();

                return View(studentSchedule);
            }
            catch (Exception ex)
            {
                //log error
                return View(new StudentScheduleModel());
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {
                student = await StudentBL.SaveAsync(student);
                return RedirectToAction(nameof(Index));
            }

            return View(student);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var student = await StudentBL.GetAsync(id);

            if (student == null)
                return NotFound();

            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Student student)
        {
            if (id != student.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                student = await StudentBL.UpdateAsync(student, id);

                return RedirectToAction(nameof(Index));
            }

            return View(student);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var course = await StudentBL.GetAsync(id);

            if (course == null)
                return NotFound();

            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            StudentBL.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

EC_English/Views/Students/Create.cshtml
@model Common.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" maxlength="500"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" maxlength="500" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" maxlength="500" type="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EC_English/Views/Students/Delete.cshtml
@model Common.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EC_English/Views/Students/Details.cshtml
@*@model Common.Models.Student*@
@model Common.CustomModels.StudentScheduleModel

@using BusinessLogic.Helpers

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>

<div>
    <h4>Schedule</h4>

    @if (Model.Schedule.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Schedule)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Type)</td>
                        <td>@Html.DisplayFor(modelItem => item.StartDate)</td>
                        <td>@Html.DisplayFor(modelItem => item.EndDate)</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No courses or holidays scheduled.</p>
    }
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EC_English/Views/Students/Edit.cshtml
@model Common.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" maxlength="500" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" maxlength="500" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" maxlength="500" type="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EC_English/Views/Students/Index.cshtml
@model IEnumerable<Common.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div>
    @using (Html.BeginForm("Index", "Students", FormMethod.Get))
    {
        @Html.TextBox("search")
        <input id="btnSearch" type="submit" value="Search" class="btn" />
    }
</div>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">View</a> |
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
                <td>
                    @{
                        var parms = new Dictionary<string, string> {
                            { "studentId", item.Id.ToString() }
                        };
                    }

                    <a asp-controller="Enrolments" asp-action="Create" asp-all-route-data="@parms">Enroll</a> |
                    <a asp-controller="Holidays" asp-action="Create" asp-all-route-data="@parms">Book Holiday</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts  {
    <script>
        $(document).ready(function () {
            $("#search").change(function () {
                $("#btnSearch").click();
            });
        });
    </script>
}